omni.replicator.object:
  focal_length: 14.228393962367306
  horizontal_aperture: 20.955
  camera_parameters:
    far_clip: 100000
    focal_length: $[/focal_length]
    horizontal_aperture: $[/horizontal_aperture]
    near_clip: 0.1
    screen_height: $[/screen_height]
    screen_width: $[/screen_width]
  carpets:
  - $[/carpets_root]/Carpet_Beige.mdl
  - $[/carpets_root]/Carpet_Berber_Gray.mdl
  carpets_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Materials/2023_1/Base/Carpet
  default_camera:
    camera_parameters: $[/camera_parameters]
    transform_operators:
    - translate_shake: $[/translate_shake_H]
    - rotateY: $[/rotateY_H]
    - rotateX: $[/rotateX_H]
    - translate: $[/distance_H]
    type: camera
  distance_H:
    distribution_type: range
    end:
    - 0
    - 0
    - 500
    start:
    - 0
    - 0
    - 400
  distant_light:
    color:
      distribution_type: range
      end:
      - 1.3
      - 1.3
      - 1.3
      start:
      - 0.7
      - 0.7
      - 0.7
    count: 5
    intensity:
      distribution_type: range
      end: 600
      start: 150
    subtype: distant
    transform_operators:
    - rotateY:
        distribution_type: range
        end: 180
        start: -180
    - rotateX:
        distribution_type: range
        end: -10
        start: -40
    type: light
  dome_light:
    color:
      distribution_type: range
      end:
      - 1.3
      - 1.3
      - 1.3
      start:
      - 0.7
      - 0.7
      - 0.7
    intensity:
      distribution_type: range
      end: 300
      start: 100
    subtype: dome
    type: light
  focal_length: 14.228393962367306
  horizontal_aperture: 20.955
  inter_frame_time: 3
  mesh:
    count: 10
    physics: rigidbody
    subtype: mesh
    tracked: true
    transform_operators:
    - translate:
        distribution_type: range
        end:
        - 100
        - 150
        - 100
        start:
        - -100
        - 50
        - -100
    - rotateX:
        distribution_type: range
        start: -180
        end: 180
    - rotateY:
        distribution_type: range
        start: -180
        end: 180
    - scale:
      - 0.5
      - 0.5
      - 0.5
    type: geometry
    usd_path:
      distribution_type: folder
      suffix: usd
      value: $[/resources_root]/main_objects
  num_frames: 3
  output_path: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/unittest_output_table_harmonizer
  pallets:
  - $[/pallets_root]/Metal/Aluminum_A/AluminumPallet_A01_PR_NVD_01.usd
  - $[/pallets_root]/Metal/Aluminum_A/AluminumPallet_A02_PR_NVD_01.usd
  - $[/pallets_root]/Metal/GalvanizedSteel_A/GalvanizedSteelPallet_A01_PR_NVD_01.usd
  pallets_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Assets/DigitalTwin/Assets/Warehouse/Shipping/Pallets
  plane:
    subtype: plane
    texture_path:
      distribution_type: folder
      suffix: jpg
      value: $[/resources_root]/background_images
    transform_operators:
    - translate_shake: $[/translate_shake_H]
    - rotateY: $[/rotateY_H]
    - rotateX: $[/rotateX_H]
    - translate: $[/distance_H]
    - translate_local:
      - 0
      - 0
      - -5000
    - rotateXYZ:
      - -90
      - 0
      - 180
    - scale:
      - 5000 / 50 * $[/horizontal_aperture] / $[/focal_length] / 2
      - 1
      - 5000 / 50 * $[/horizontal_aperture] / $[/focal_length] / 2 * $[/screen_height]
        / $[/screen_width]
    type: geometry
  resources_root: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/fst02_unittest_v1
  resources_root_2: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/fst02_unittest_v2
  rotateX_H:
    distribution_type: range
    end: -20
    start: -50
  rotateY_H:
    distribution_type: range
    end: 180
    start: -180
  screen_height: 544
  screen_width: 960
  seed: 2
  skies:
  - $[/skies_root]/2022_1/Skies/Clear/lakeside.hdr
  - $[/skies_root]/2022_1/Skies/Clear/mealie_road.hdr
  - $[/skies_root]/2022_1/Skies/Clear/noon_grass.hdr
  skies_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Assets/Skies
  translate_shake_H:
    distribution_type: range
    end:
    - 100
    - 100
    - 100
    start:
    - -100
    - -100
    - -100
  version: 0.3.5
