omni.replicator.object:
  camera_parameters:
    far_clip: 100000
    focal_length: 14.228393962367306
    horizontal_aperture: 20.955
    near_clip: 0.1
    screen_height: $[/screen_height]
    screen_width: $[/screen_width]
  carpets:
  - $[/carpets_root]/Carpet_Beige.mdl
  - $[/carpets_root]/Carpet_Berber_Gray.mdl
  carpets_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Materials/2023_1/Base/Carpet
  default_camera:
    camera_parameters: $[/camera_parameters]
    transform_operators:
    - rotateY:
        distribution_type: range
        end: 180
        start: -180
    - rotateX: -30
    - translate:
        distribution_type: range
        end:
        - 0
        - 0
        - 800
        start:
        - 0
        - 0
        - 600
    type: camera
  dome_light:
    intensity:
      distribution_type: range
      end: 3000
      start: 1000
    subtype: dome
    texture_path:
      distribution_type: set
      values: $[/skies]
    transform_operators:
    - rotateX: 270
    type: light
  friction: 0.3
  gravity: 10000
  inter_frame_time: 1
  linear_damping: 4
  mesh:
    count: 10
    physics: rigidbody
    subtype: mesh
    tracked: true
    transform_operators:
    - translate:
        distribution_type: range
        end:
        - 50
        - 100
        - 50
        start:
        - -50
        - 100
        - -50
    - scale:
      - 0.5
      - 0.5
      - 0.5
    type: geometry
    usd_path:
      distribution_type: folder
      suffix: usd
      value: $[/resources_root]/main_objects
  num_frames: 3
  output_path: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/unittest_output_table
  pallets:
  - $[/pallets_root]/Metal/Aluminum_A/AluminumPallet_A01_PR_NVD_01.usd
  - $[/pallets_root]/Metal/Aluminum_A/AluminumPallet_A02_PR_NVD_01.usd
  - $[/pallets_root]/Metal/GalvanizedSteel_A/GalvanizedSteelPallet_A01_PR_NVD_01.usd
  pallets_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Assets/DigitalTwin/Assets/Warehouse/Shipping/Pallets
  plane: None
  resources_root: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/fst02_unittest_v1
  resources_root_2: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/fst02_unittest_v2
  screen_height: 544
  screen_width: 960
  seed: 2
  skies:
  - $[/skies_root]/2022_1/Skies/Clear/lakeside.hdr
  - $[/skies_root]/2022_1/Skies/Clear/mealie_road.hdr
  - $[/skies_root]/2022_1/Skies/Clear/noon_grass.hdr
  skies_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Assets/Skies
  table:
    physics: collision
    subtype: mesh
    type: geometry
    usd_path:
      distribution_type: set
      values:
      - $[/resources_root_2]/Table_and_Chairs/table_and_chairs.usdc
      - $[/resources_root_2]/Wooden_Table/wooden_table.usdc
  version: 0.3.5
