omni.replicator.object:
  basic_shape:
    color:
    - 0.5 + 0.5 * math.cos(2 * math.pi * $[index] / $[count])
    - 0.5 + 0.5 * math.cos(2 * math.pi * ($[index] / $[count] + 0.33))
    - 0.5 + 0.5 * math.cos(2 * math.pi * ($[index] / $[count] + 0.67))
    count: 10
    subtype: torus
    transform_operators:
    - translate:
      - 10
      - math.sin($[../index] / 2 + 2) * 60
      - ($[../index] - ($[../count] - 1) / 2) * 50
    - rotateX:
        distribution_type: range
        start: -180
        end: 180
    - rotateY:
        distribution_type: range
        start: -180
        end: 180
    - scale:
      - $[/torus_size]
      - $[/torus_size]
      - $[/torus_size]
    type: geometry
  camera_parameters:
    far_clip: 100000
    focal_length: 14.228393962367306
    horizontal_aperture: 20.955
    near_clip: 0.1
    screen_height: $[/screen_height]
    screen_width: $[/screen_width]
  carpets:
  - $[/carpets_root]/Carpet_Beige.mdl
  - $[/carpets_root]/Carpet_Berber_Gray.mdl
  carpets_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Materials/2023_1/Base/Carpet
  default_camera:
    camera_parameters: $[/camera_parameters]
    transform_operators:
    - rotateY: 90
    - rotateX: -10
    - translate:
      - 0
      - 0
      - 600
    type: camera
  dome_light:
    intensity:
      distribution_type: range
      end: 3000
      start: 1000
    subtype: dome
    texture_path:
      distribution_type: set
      values: $[/skies]
    transform_operators:
    - rotateX: 270
    type: light
  focal_length: 14.228393962367306
  gravity: 10000
  horizontal_aperture: 20.955
  num_frames: 3
  output_path: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/unittest_output_kaleidoscope
  pallets:
  - $[/pallets_root]/Metal/Aluminum_A/AluminumPallet_A01_PR_NVD_01.usd
  - $[/pallets_root]/Metal/Aluminum_A/AluminumPallet_A02_PR_NVD_01.usd
  - $[/pallets_root]/Metal/GalvanizedSteel_A/GalvanizedSteelPallet_A01_PR_NVD_01.usd
  pallets_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Assets/DigitalTwin/Assets/Warehouse/Shipping/Pallets
  plane: None
  resources_root: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/fst02_unittest_v1
  resources_root_2: /home/jenkins/agent/workspace/dev-omni-replicator-retail-docker-L0/fst02_unittest_v2
  screen_height: 544
  screen_width: 960
  seed: 2
  skies:
  - $[/skies_root]/2022_1/Skies/Clear/lakeside.hdr
  - $[/skies_root]/2022_1/Skies/Clear/mealie_road.hdr
  - $[/skies_root]/2022_1/Skies/Clear/noon_grass.hdr
  skies_root: omniverse://isaac-dev.ov.nvidia.com/NVIDIA/Assets/Skies
  torus_size: 0.5
  version: 0.3.5
