omni.replicator.object:
  version: 0.3.5
  parent_config: table
  friction: 0.3
  gravity: 10000
  inter_frame_time: 3
  linear_damping: 4
  dome_light: None # suppress parent config
  bright_light:
    type: light
    subtype: dome
    intensity:
      distribution_type: range
      start:
        distribution_type: range
        start: $[/dark_light/intensity]
        end: $[/dark_light/intensity] + 200
      end: $[/dark_light/intensity] + 1000
    texture_path: omniverse://content.ov.nvidia.com/NVIDIA/Assets/Skies/2022_1/Skies/Clear/lakeside.hdr
    transform_operators:
    - rotateX: 270
  dark_light:
    subtype: dome
    intensity:
      distribution_type: range
      start: 100
      end: 1000
  default_camera:
    type: camera
    camera_parameters: $[/camera_parameters]
    transform_operators:
    - rotateY:
        distribution_type: range
        end: 180
        start: -180
    - rotateX: -30
    - translate:
        distribution_type: range
        end:
        - 0
        - 0
        - 800
        start:
        - 0
        - 0
        - 600
  # table:
  #   physics: collision
  #   subtype: mesh
  #   type: geometry
  #   usd_path: omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/Desks/Desk_01.usd
  #   transform_operators:
  #   - translate:
  #     - 15
  #     - -170
  #     - 0
  #   - rotateXYZ:
  #     - -90
  #     - 0
  #     - 0
  #   - scale:
  #     - 2.2
  #     - 2.2
  #     - 2.2
  mesh:
    count: 10
    physics: rigidbody
    subtype: mesh
    tracked: true
    transform_operators:
    - translate:
        distribution_type: range
        end:
        - 50
        - 100
        - 50
        start:
        - -50
        - 100
        - -50
    - scale:
      - 0.5
      - 0.5
      - 0.5
    type: geometry
    usd_path:
      distribution_type: folder
      suffix: usd
      value: /home/startup/Desktop/2024/common/boxes #PATH_TO_BOXES
  plane:
    material_path:
      distribution_type: set
      values: $[/carpets]
    physics: collision
    subtype: plane
    transform_operators:
    - rotateY:
        distribution_type: range
        end: 180
        start: -180
    - scale:
      - 7
      - 1
      - 7
  output_name: demo_table_$[seed]