omni.replicator.object:
  version: 0.3.5
  parent_config: standard
  seed: 20
  bin_pack_H:
    harmonizer_type: bin_pack
    bin_size:
    - 400
    - 200
    - 200
  mesh:
    count: 30
    #physics: rigidbody
    subtype: mesh
    tracked: true
    transform_operators:
    - transform:
        distribution_type: harmonized
        harmonizer_name: bin_pack_H
        pitch: local_aabb
    - scale:
      - 1
      - 1
      - 1
    type: geometry
    usd_path:
      distribution_type: folder
      suffix: usd
      value: PATH_TO_BOXES