omni.replicator.object:
  gravity: 10000
  mesh:
    count: 60
    physics: rigidbody
    subtype: mesh
    tracked: true
    transform_operators:
    - translate_shelf:
      - 0
      - ($[../index] // 5 % 3 - 3 / 2 + 0.5) * 100
      - ($[../index] // 5 // 3 - 4 / 2 + 0.5) * 200
    - translate:
      - 0
      - $[../index] % 5 * 14
      - 0
    - rotateY:
        distribution_type: range
        end: 15
        start: -15
    - rotateXYZ:
      - 0
      - -90
      - -90
    type: geometry
    usd_path:
      distribution_type: set
      values: $[/pallets]
  parent_config: standard
  plane:
    material_path:
      distribution_type: set
      values: $[/carpets]
    physics: collision
    subtype: plane
    transform_operators:
    - translate:
      - 0
      - -120
      - 0
    - scale:
      - 10
      - 10
      - 10
    type: geometry
  rack:
    count: 4
    physics: collision
    subtype: mesh
    tracked: false
    transform_operators:
    - translate:
      - 10
      - -120
      - ($[../index] - ($[../count] - 1) / 2) * 200
    - rotateXYZ:
      - 0
      - -90
      - -90
    - scale:
      - 1.24
      - 1.44
      - 1.6
    type: geometry
    usd_path: omniverse://content.ov.nvidia.com/NVIDIA/Assets/DigitalTwin/Assets/Warehouse/Shelving/Racks/Rack_L/Rack_L02_PR_NVD_01.usd
  shelf: 1
  version: 0.3.5
