omni.replicator.object:
  parent_config: global
  default_camera:
    camera_parameters: $[/camera_parameters]
    transform_operators:
    - rotateY:
        distribution_type: range
        start: -180
        end: 180
    - rotateX: -30
    - translate:
        distribution_type: range
        start:
        - 0
        - 0
        - 600
        end:
        - 0
        - 0
        - 800
    type: camera
  dome_light:
    intensity:
      distribution_type: range
      start: 500
      end: 3000
    subtype: dome
    transform_operators:
    - rotateX: 270
    type: light
  version: 0.3.5
