omni.replicator.object:
  friction: 0.3
  gravity: 10000
  inter_frame_time: 1
  linear_damping: 4
  parent_config: standard
  seed: 0
  num_frames: 3
  table:
    physics: collision
    subtype: mesh
    type: geometry
    selected_index:
      distribution_type: range
      start: 0
      end: 8
    usd_path:
      distribution_type: set
      values:
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/Desks/Desk_01.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/DiningSets/DesPeres/DesPeres_Table.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/DiningSets/EastRural/EastRural_Table.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/DiningSets/Jennings/Jennings_Table.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/FurnitureSets/Appleseed/Appleseed_CoffeeTable.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/MediaTables/CreveCoeur.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/MediaTables/Soulard.usd
      - omniverse://content.ov.nvidia.com/NVIDIA/Assets/ArchVis/Residential/Furniture/Tables/Whittershins.usd
      index: $[/table/selected_index] # need to support relative indexing
    transform_operators:
    - translate_local:
        distribution_type: set
        values:
        - - 15
          - -170
          - 0
        - - 40
          - -160
          - 50
        - - 30
          - -180
          - 0
        - - 30
          - -175
          - 10
        - - 30
          - -175
          - 20
        - - 40
          - -165
          - 20
        - - 35
          - -165
          - 25
        - - 25
          - -170
          - 30
        index: $[/table/selected_index]
    - rotateXYZ:
        distribution_type: set
        values:
        - - -90
          - 0
          - 0
        - - 0
          - -90
          - -90
        - - -90
          - 0
          - 0
        - - 0
          - -90
          - -90
        - - 0
          - -90
          - -90
        - - 0
          - -90
          - -90
        - - 0
          - -90
          - -90
        - - 0
          - -90
          - -90
        index: $[/table/selected_index]
    - scale:
        distribution_type: set
        values:
        - - 2.2
          - 2.2
          - 2.2
        - - 2.1
          - 2.1
          - 2.1
        - - 2.5
          - 2.5
          - 2.5
        - - 2.4
          - 2.4
          - 2.4
        - - 4.1
          - 4.1
          - 4.1
        - - 4.1
          - 4.1
          - 4.1
        - - 3.3
          - 3.3
          - 3.3
        - - 2.9
          - 2.9
          - 2.9
        index: $[/table/selected_index]
  version: 0.3.5
