omni.replicator.object:
  num_frames: 3 #3
  seed: 0
  output_path: /home/startup/Desktop/2024/common/output/1004_3 #PATH_TO_OUTPUT
  screen_height: 2160
  screen_width: 3840
  focal_length: 14.228393962367306
  horizontal_aperture: 20.955
  camera_parameters:
    screen_width: $[/screen_width]
    screen_height: $[/screen_height]
    focal_length: $[/focal_length]
    horizontal_aperture: $[/horizontal_aperture]
    near_clip: 0.1
    far_clip: 100000
  path_to_boxes: PATH_TO_BOXES
  path_to_oro: PATH_TO_ORO
  nucleus_root: omniverse://content.ov.nvidia.com/NVIDIA-Staging
  aws_root: https://omniverse-content-staging.s3-us-west-2.amazonaws.com
  server_root: $[/aws_root]
  carpets:
  - $[carpets_root]/Carpet_Beige.mdl
  - $[carpets_root]/Carpet_Berber_Gray.mdl
  - $[carpets_root]/Carpet_Berber_Multi.mdl
  - $[carpets_root]/Carpet_Charcoal.mdl
  - $[carpets_root]/Carpet_Cream.mdl
  - $[carpets_root]/Carpet_Diamond_Olive.mdl
  - $[carpets_root]/Carpet_Diamond_Yellow.mdl
  - $[carpets_root]/Carpet_Forest.mdl
  - $[carpets_root]/Carpet_Gray.mdl
  - $[carpets_root]/Carpet_Pattern_Leaf_Squares_Tan.mdl
  - $[carpets_root]/Carpet_Pattern_Loop.mdl
  - $[carpets_root]/Carpet_Pattern_Squares_Multi.mdl
  carpets_root: $[/server_root]/Materials/2023_1/Base/Carpet
  pallets:
  - $[pallets_root]/Metal/Aluminum_A/AluminumPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Metal/Aluminum_A/AluminumPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Metal/GalvanizedSteel_A/GalvanizedSteelPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/ClosedDeckExport_A/ClosedDeckExportPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Drum_A/PlasticDrumPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Economy_A/EconomyPlasticPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Economy_A/EconomyPlasticPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Economy_A/EconomyPlasticPallet_A03_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A03_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A04_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A05_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A06_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Export_A/ExportPallet_A07_PR_NVD_01.usd
  - $[pallets_root]/Plastic/HeavyDutyNestable_A/HeavyDutyNestablePallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/HeavyDutyNestable_A/HeavyDutyNestablePallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Industrial_A/IndustrialPlasticPallet_A01_PR_V_NVD_01.usd
  - $[pallets_root]/Plastic/RackableExport_A/RackableExportPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Plastic/Rackable_A/RackablePallet_A01_PR_V_NVD_01.usd
  - $[pallets_root]/Plastic/Rackable_A/RackablePallet_A02_PR_V_NVD_01.usd
  - $[pallets_root]/Plastic/SolidTopRackable_A/SolidTopRackablePallet_A01_PR_V_NVD_01.usd
  - $[pallets_root]/Plastic/SolidTopRackable_A/SolidTopRackablePallet_A02_PR_V_NVD_01.usd
  - $[pallets_root]/Plastic/SolidTopRackable_A/SolidTopRackablePallet_A03_PR_V_NVD_01.usd
  - $[pallets_root]/Plastic/SolidTopRackable_A/SolidTopRackablePallet_A04_PR_V_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A03_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A04_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A05_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A06_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A07_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A08_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_A/BlockPallet_A09_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_B/BlockPallet_B01_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_B/BlockPallet_B02_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_B/BlockPallet_B03_PR_NVD_01.usd
  - $[pallets_root]/Wood/Block_C/BlockPallet_C01_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A03_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A04_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A05_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A06_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A07_PR_NVD_01.usd
  - $[pallets_root]/Wood/Drum_A/WoodDrumPallet_A08_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A03_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A04_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A05_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A06_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A07_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A08_PR_NVD_01.usd
  - $[pallets_root]/Wood/Pressed_A/PressedWoodPallet_A09_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A01_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A02_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A03_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A04_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A05_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A06_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A07_PR_NVD_01.usd
  - $[pallets_root]/Wood/Recycled_A/RecycledWoodPallet_A08_PR_NVD_01.usd
  - $[pallets_root]/Wood/Wing_A/WingPallet_A01_PR_NVD_01.usd
  pallets_root: $[/server_root]/Assets/DigitalTwin/Assets/Warehouse/Shipping/Pallets
  skies:
  - $[skies_root]/2022_1/Skies/Clear/lakeside.hdr
  - $[skies_root]/2022_1/Skies/Clear/mealie_road.hdr
  - $[skies_root]/2022_1/Skies/Clear/noon_grass.hdr
  - $[skies_root]/2022_1/Skies/Clear/qwantani.hdr
  - $[skies_root]/2022_1/Skies/Clear/signal_hill_sunrise.hdr
  - $[skies_root]/2022_1/Skies/Clear/syferfontein_18d_clear.hdr
  - $[skies_root]/2022_1/Skies/Cloudy/between_bridges.hdr
  - $[skies_root]/2022_1/Skies/Cloudy/champagne_castle_1.hdr
  - $[skies_root]/2022_1/Skies/Cloudy/kloofendal_48d_partly_cloudy.hdr
  - $[skies_root]/2022_1/Skies/Cloudy/sunflowers.hdr
  - $[skies_root]/2022_1/Skies/Cloudy/table_mountain_1.hdr
  - $[skies_root]/2022_1/Skies/Cloudy/white_cliff_top.hdr
  - $[skies_root]/2022_1/Skies/Evening/evening_road_01.hdr
  - $[skies_root]/2022_1/Skies/Indoor/ZetoCG_com_WarehouseInterior2b.hdr
  - $[skies_root]/2022_1/Skies/Indoor/ZetoCGcom_ExhibitionHall_Interior1.hdr
  - $[skies_root]/2022_1/Skies/Indoor/adams_place_bridge.hdr
  - $[skies_root]/2022_1/Skies/Indoor/autoshop_01.hdr
  - $[skies_root]/2022_1/Skies/Indoor/small_hangar_01.hdr
  - $[skies_root]/2022_1/Skies/Night/kloppenheim_02.hdr
  - $[skies_root]/2022_1/Skies/Night/moonlit_golf.hdr
  - $[skies_root]/2022_1/Skies/Sky_Elements/materials/cloudy/textures/ambient4.hdr
  - $[skies_root]/2022_1/Skies/Sky_Elements/materials/cloudy/textures/stars_4k.hdr
  - $[skies_root]/2022_1/Skies/Storm/approaching_storm.hdr
  - $[skies_root]/2022_1/Skies/Studio/carlight.hdr
  - $[skies_root]/2022_1/Skies/Studio/lightbox.hdr
  - $[skies_root]/2022_1/Skies/Studio/lightbox01.hdr
  - $[skies_root]/2022_1/Skies/Studio/lightbox02.hdr
  - $[skies_root]/Clear/evening_road_01_4k.hdr
  - $[skies_root]/Clear/kloppenheim_02_4k.hdr
  - $[skies_root]/Clear/mealie_road_4k.hdr
  - $[skies_root]/Clear/noon_grass_4k.hdr
  - $[skies_root]/Clear/qwantani_4k.hdr
  - $[skies_root]/Clear/signal_hill_sunrise_4k.hdr
  - $[skies_root]/Clear/sunflowers_4k.hdr
  - $[skies_root]/Clear/syferfontein_18d_clear_4k.hdr
  - $[skies_root]/Clear/venice_sunset_4k.hdr
  - $[skies_root]/Clear/white_cliff_top_4k.hdr
  - $[skies_root]/Cloudy/abandoned_parking_4k.hdr
  - $[skies_root]/Cloudy/champagne_castle_1_4k.hdr
  - $[skies_root]/Cloudy/evening_road_01_4k.hdr
  - $[skies_root]/Cloudy/kloofendal_48d_partly_cloudy_4k.hdr
  - $[skies_root]/Cloudy/lakeside_4k.hdr
  - $[skies_root]/Cloudy/sunflowers_4k.hdr
  - $[skies_root]/Cloudy/table_mountain_1_4k.hdr
  - $[skies_root]/Evening/evening_road_01_4k.hdr
  - $[skies_root]/Indoor/ZetoCG_com_WarehouseInterior2b.hdr
  - $[skies_root]/Indoor/ZetoCGcom_ExhibitionHall_Interior1.hdr
  - $[skies_root]/Indoor/adams_place_bridge_4k.hdr
  - $[skies_root]/Indoor/autoshop_01_4k.hdr
  - $[skies_root]/Indoor/bathroom_4k.hdr
  - $[skies_root]/Indoor/carpentry_shop_01_4k.hdr
  - $[skies_root]/Indoor/en_suite_4k.hdr
  - $[skies_root]/Indoor/entrance_hall_4k.hdr
  - $[skies_root]/Indoor/hospital_room_4k.hdr
  - $[skies_root]/Indoor/hotel_room_4k.hdr
  - $[skies_root]/Indoor/lebombo_4k.hdr
  - $[skies_root]/Indoor/old_bus_depot_4k.hdr
  - $[skies_root]/Indoor/small_empty_house_4k.hdr
  - $[skies_root]/Indoor/studio_small_04_4k.hdr
  - $[skies_root]/Indoor/surgery_4k.hdr
  - $[skies_root]/Indoor/vulture_hide_4k.hdr
  - $[skies_root]/Indoor/wooden_lounge_4k.hdr
  - $[skies_root]/Night/kloppenheim_02_4k.hdr
  - $[skies_root]/Night/moonlit_golf_4k.hdr
  - $[skies_root]/Sky_Elements/materials/cloudy/textures/ambient4.hdr
  - $[skies_root]/Sky_Elements/materials/cloudy/textures/stars_4k.hdr
  - $[skies_root]/Storm/approaching_storm_4k.hdr
  - $[skies_root]/Studio/photo_studio_01_4k.hdr
  - $[skies_root]/Studio/studio_small_05_4k.hdr
  - $[skies_root]/Studio/studio_small_07_4k.hdr
  skies_root: $[/server_root]/Assets/Isaac/4.2/NVIDIA/Assets/Skies
  cardboard_boxes:
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A01_10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A02_16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A03_21cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A04_26cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A05_32cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A06_42cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A07_52cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A08_62cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A09_77cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Cube_A/CubeBox_A10_92cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A01_15x16x6cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A02_15x21x8cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A03_23x22x11cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A04_20x26x12cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A05_26x26x11cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A06_28x30x8cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A07_26x32x11cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A08_31x30x8cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A09_32x32x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A10_26x56x11cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A11_25x30x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A12_56x56x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A13_36x61x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A14_44x60x8cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A15_51x63x33cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Flat_A/FlatBox_A16_51x61x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A01_8x16x8xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A02_21x51x11xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A03_16x51x16xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A04_11x51x10xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A05_16x46x16xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A06_11x46x10xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A07_16x41x16xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A08_16x31x15xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A09_16x31x6xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A10_16x26x16xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A11_11x26x10xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Long_A/LongBox_A12_11x21x10xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A01_20x20x21cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A02_20x25x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A03_25x25x31cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A04_15x31x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A05_31x31x31cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A06_20x36x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A07_36x36x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A08_36x41x16cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A09_41x41x42cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A10_31x46x31cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A11_46x46x31cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Multi-Depth_A/MultiDepthBox_A12_36x51x36xcm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A01_28x44x25cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A02_21x28x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A03_23x28x12cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A04_22x28x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A05_23x28x25cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A06_23x31x5cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A07_23x31x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A08_22x31x22cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A09_23x30x14cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/Printer_A/PrintersBox_A10_28x44x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A01_10x10x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A02_13x13x13cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A03_15x15x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A04_18x18x18cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A05_20x20x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A06_23x23x23cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A07_25x25x25cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A08_30x30x30cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A09_36x36x36cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A10_40x41x42cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A11_46x47x47cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A12_51x52x52cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A13_61x61x61cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A14_30x30x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A15_30x30x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A16_30x30x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A17_30x47x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A18_30x47x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A19_30x47x30cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A20_30x62x30cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A21_30x38x25cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A22_30x41x30cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A23_15x20x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A24_20x26x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A25_25x30x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A26_25x37x25cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A27_22x30x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A28_22x29x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A29_22x29x31cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A30_23x30x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A31_25x30x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A32_30x30x25cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A33_20x20x15cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A34_16x16x10cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A35_20x30x20cm_PR_NVD_01.usd
  - $[cardboard_boxes_root]/White_A/WhiteCorrugatedBox_A36_22x30x20cm_PR_NVD_01.usd
  cardboard_boxes_root: $[/server_root]/Assets/DigitalTwin/Assets/Warehouse/Shipping/Cardboard_Boxes
  version: 0.3.10
